# Criticality Rules Configuration
# Defines how actions are classified for human approval

# VIP contacts that always require high criticality approval
vip_contacts:
  - "CEO"
  - "CTO"
  - "Investor"
  - "Board Member"
  - "Client Manager"
  - "Legal"
  - "HR Director"

# Default criticality levels for action types
action_defaults:
  email_send: "medium"
  email_reply: "medium"
  calendar_create: "medium"
  calendar_modify: "high"
  calendar_cancel: "high"
  call_make: "high"
  sms_send: "medium"
  file_create: "low"
  file_modify: "medium"
  file_delete: "high"
  task_create: "low"
  task_modify: "low"
  task_complete: "low"
  reminder_set: "low"
  focus_session: "low"
  archive: "low"
  log: "low"
  search: "low"
  analyze: "low"
  document_send: "high"
  contract_sign: "high"
  payment_send: "high"
  
# Keyword patterns that influence criticality
keyword_patterns:
  high:
    - "urgent"
    - "emergency"
    - "critical"
    - "asap"
    - "deadline"
    - "important meeting"
    - "board"
    - "investor"
    - "legal"
    - "contract"
    - "payment"
    - "salary"
    - "termination"
    - "firing"
    - "confidential"
    - "nda"
    - "acquisition"
    - "merger"
    
  medium:
    - "important"
    - "priority"
    - "review"
    - "approve"
    - "meeting"
    - "presentation"
    - "demo"
    - "proposal"
    - "client"
    - "customer"
    - "feedback"
    - "update"
    
  low:
    - "fyi"
    - "archive"
    - "log"
    - "reminder"
    - "note"
    - "casual"
    - "informal"
    - "routine"

# Domain-based rules
domain_rules:
  # Email domains that require high criticality
  high_priority_domains:
    - "board.company.com"
    - "legal.company.com"
    - "investors.company.com"
    - "c-suite.company.com"
    
  # Internal domains that can be medium/low
  internal_domains:
    - "company.com"
    - "internal.company.com"
    - "team.company.com"

# Time-based sensitivity rules
time_sensitive:
  # Business hours (24-hour format)
  business_hours:
    start: 9
    end: 18
    
  # Timezone
  timezone: "America/New_York"
  
  # Increase criticality outside business hours
  increase_criticality_outside_hours: true
  
  # Weekend handling
  weekend_handling:
    increase_criticality: true
    emergency_only: false  # If true, only emergency actions on weekends

# Financial thresholds
financial_thresholds:
  # Payment amounts that require high criticality
  high_amount: 10000  # $10,000+
  medium_amount: 1000  # $1,000+
  
  # Currency patterns to detect
  currency_patterns:
    - "\\$[0-9,]+"
    - "USD [0-9,]+"
    - "[0-9,]+ dollars"

# Context-based rules
context_rules:
  # If action is part of a sequence, inherit criticality
  inherit_from_sequence: true
  
  # If action is a followup, reduce criticality
  reduce_followup_criticality: true
  
  # If action is automated/scheduled, can be lower criticality
  reduce_automated_criticality: true

# Learning and adaptation settings
learning:
  # Enable learning from user feedback
  enabled: true
  
  # Minimum feedback entries before adjusting rules
  min_feedback_count: 10
  
  # Confidence threshold for automatic rule adjustment
  confidence_threshold: 0.85
  
  # Maximum automatic criticality adjustment
  max_auto_adjustment: 1  # Can move up/down by 1 level max

# Override rules for specific patterns
overrides:
  # Specific action + target combinations
  specific_overrides:
    - pattern: "email_send to CEO*"
      criticality: "high"
      reason: "All emails to CEO require approval"
      
    - pattern: "calendar_* with *board*"
      criticality: "high"
      reason: "Board-related calendar events need approval"
      
    - pattern: "file_delete *important*"
      criticality: "high"
      reason: "Deleting important files needs approval"
      
    - pattern: "task_create *urgent*"
      criticality: "medium"
      reason: "Urgent tasks should be reviewed"

# Approval timeout settings by criticality
timeout_settings:
  high:
    timeout_minutes: 5
    escalation_enabled: true
    escalation_channels: ["call", "sms"]
    
  medium:
    timeout_minutes: 15
    escalation_enabled: true
    escalation_channels: ["sms"]
    
  low:
    timeout_minutes: 60
    escalation_enabled: false
    escalation_channels: []

# Alert preferences by criticality
alert_preferences:
  high:
    channels: ["call", "sms", "notification"]
    repeat_interval: 2  # minutes
    max_repeats: 3
    
  medium:
    channels: ["sms", "notification"]
    repeat_interval: 5
    max_repeats: 2
    
  low:
    channels: ["notification"]
    repeat_interval: 0  # no repeats
    max_repeats: 0